language: android
script:
  - ./gradlew build
branches:
  only:
    - master
android:
  components:
    - android-22
    - build-tools-22.0.1
    - extra-android-support
    - extra-android-m2repository

jdk:
  - oraclejdk7
  - oraclejdk8

notifications:
  email:
    false