language: android
android:
  components:
    - android-22
    - build-tools-22.0.1
    - extra-android-support
    - extra-android-m2repository

  branches:
    only:
      - master

  script:
    - ./gradlew build

  notifications:
    email:
      false