language: android
android:
  components:
    - android-22
    - build-tools-22.0.1
    - extra-android-support
    - extra-android-m2repository

  jdk:
    - oraclejdk7
    - oraclejdk8

  branches:
    only:
      - master

  install:
    - true

  script: ./gradlew assemble test

  notifications:
    email:
      false